name: CI
on: [push]
jobs:
  javascript:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./javascript
    strategy:
      matrix:
        node: ["12.x", "14.x", "16.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

  rust:
    name: Build and test on Rust ${{ matrix.toolchain }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./rust
    strategy:
      matrix:
        toolchain: [nightly, stable]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - run: cargo build --release --all-features

      - run: cargo test

  dart:
    name: Build and test on Dart ${{ matrix.sdk }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./dart
    strategy:
      matrix:
        sdk: [stable, beta]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
